```sql
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE APE_DTS.GDBO_ORA_PRECHECK_BASIC PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
```

CREATE TABLE APE_DTS.GDBO_ORA_PRECHECK_BASIC (
  ID NUMBER(19) PRIMARY KEY,
  VAL VARCHAR2(100)
);

