DO $$
BEGIN
  EXECUTE 'CREATE SCHEMA "APE_DTS"';
EXCEPTION
  WHEN duplicate_schema THEN
    NULL;
END$$;

DROP TABLE IF EXISTS "APE_DTS"."GDBO_ORA_PRECHECK_BASIC";
CREATE TABLE "APE_DTS"."GDBO_ORA_PRECHECK_BASIC" (
  "ID" BIGINT PRIMARY KEY,
  "VAL" TEXT
);
