```sql
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE APE_DTS.GDBO_ORA_SNAP_SMOKE PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
```

CREATE TABLE APE_DTS.GDBO_ORA_SNAP_SMOKE (
  ID NUMBER(10) PRIMARY KEY,
  VAL VARCHAR2(100)
);

