CREATE TABLE IF NOT EXISTS tasks (
    id                 TEXT PRIMARY KEY NOT NULL,
    task_id            TEXT NOT NULL UNIQUE,
    name               TEXT NOT NULL DEFAULT '',
    kind               TEXT NOT NULL CHECK (kind IN ('snapshot', 'cdc', 'check', 'struct')),
    db_type_source     TEXT NOT NULL,
    db_type_target     TEXT NOT NULL,
    source_endpoint    TEXT NOT NULL DEFAULT '{}',
    target_endpoint    TEXT NOT NULL DEFAULT '{}',
    extractor_config   TEXT NOT NULL DEFAULT '{}',
    filter_config      TEXT NOT NULL DEFAULT '{}',
    router_config      TEXT NOT NULL DEFAULT '{}',
    parallelizer_config TEXT NOT NULL DEFAULT '{}',
    pipeline_config    TEXT NOT NULL DEFAULT '{}',
    resumer_config     TEXT NOT NULL DEFAULT '{}',
    processor_config   TEXT NOT NULL DEFAULT '{}',
    runtime_config     TEXT NOT NULL DEFAULT '{}',
    metrics_config     TEXT NOT NULL DEFAULT '{}',
    resource_group_id  TEXT NOT NULL,
    owner_user_id      TEXT,
    status             TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'ready', 'running', 'paused', 'stopping', 'finished', 'failed', 'stopped')),
    created_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    FOREIGN KEY (resource_group_id) REFERENCES resource_groups(id),
    FOREIGN KEY (owner_user_id) REFERENCES users(id)
);
