[package]
name = "dt-console-server"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[features]
metrics = ["dt-common/metrics"]

[dependencies]
dt-common = { path = "../dt-common", version = "0.1.0" }

actix-web = { workspace = true }
actix-session = { workspace = true, features = ["cookie-session"] }
actix-cors = { workspace = true }
actix-files = { workspace = true }
actix-web-lab = { workspace = true }
sqlx = { workspace = true, features = ["sqlite"] }
thiserror = { workspace = true }
bcrypt = { workspace = true }
cookie = { workspace = true }
prometheus-parse = { workspace = true }
csnmp = { workspace = true }
dashmap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
regex = { workspace = true }
sha2 = { workspace = true }
base64 = { workspace = true }
