INSERT INTO APE_DTS.ORA_GDBO_CDC_BASIC (ID, VAL) VALUES (1, 'a');
INSERT INTO APE_DTS.ORA_GDBO_CDC_BASIC (ID, VAL) VALUES (2, 'b');
UPDATE APE_DTS.ORA_GDBO_CDC_BASIC SET VAL = 'bb' WHERE ID = 2;
DELETE FROM APE_DTS.ORA_GDBO_CDC_BASIC WHERE ID = 1;
COMMIT;

